import Head from 'next/head'
import Header from './Header'

export default function Layout() {
  return (
    <div>
      <Head>
        <title>Samat Pelit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header/>
    </div>
     
  )
}
