import Head from "next/head"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import styles from "@/styles/Layout.module.css"

export default function Layout({ children }) {
  return (
    <div className={styles.layout}>
      <Head>
        <title>Samat Pelit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jallutähti.jpg" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  )
}
